### ISSUE TITLE
morphisms of refined symbol contexts

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/type-refinements-for-the-working-class#6]
Morphisms of symbol contexts are sort-preserving, injective renamings. On the other hand, the refined symbol contexts are a bit more complicated, in two respects:

1. They support dependency
2. Refinements form a lattice, and we should support renamings like `u : φ --> u : ψ` when `φ` is a "subrefinement" of `ψ`. (Or maybe this is backwards, I always get variance mixed up)

Then, we want to say that `Υ || φ refines τ` when for all renamings `ρ : Υ --> Υ'`, we know what PER on closed `Υ'`-abts `φ` denotes, such that this characterization is functorial over `ρ`. That is, part of being a refinement is that you must respect renamings.

Now, the above all sounds pretty circular, but I believe that it is merely inductive-recursive, and that its well-foundedness can be established by induction on the length of `Υ`.

--------------------------------------------------------------------------------------

Including the inclusions of subrefinements in the morphisms of refined symbol contexts allows us to do some super interesting stuff globally. For instance, let's say that we have an ABT signature for telescopes like this:

```
Sort tele.
Sort type.
Sort expr.

Y !!- nil : ()tele.
Y, u:expr !!- snoc[u] : ({}[].tele, {}[].type)tele
```

Note that at the syntactic layer, there's nothing enforcing that telescopes are "well-scoped"; that is, all the names/symbols used in the telescope can occur anywhere in the telescope. We'll use refinements in order to enforce that names are only used after their "declaration".

Then, let the `Top[τ]` refine any sort `τ` as the PER that identifies all `τ`-terms; let `D[τ]` be the discrete refinement of `τ` (i.e. identifies `τ`-terms up to alpha-equivalence). Then, we can introduce refinements for telescopes that enforce well-formedness. Let's define the refinement `TELE`, intending that it shall include only the well-formed/well-scoped telescopes.

```
-----------------------
 Φ || nil() = nil() in TELE


    Φ, u : Top[expr] || A = A' in D[type]
    Φ, u : Top[expr] || H = H' in TELE
------------------------------------------------------------------------
   Φ, u : D[expr] || snoc[u](H; A) = snoc[u](H'; A') in TELE
```

Why couldn't we have just made the above premises like `Φ || H = H' in TELE`? Because the presupposition of this judgment would not be satisfied, since we only have that the syntactic assertion `Y,u:expr || H : tele`, not necessarily `Y || H : tele`. Furthermore, imagine that we were working in a computational type theory; then `D[τ]` would be replaced with `Base[τ]`, which identifies the `τ`-terms up to Kleene/Howe equivalence. In this case, we may have a term which uses the symbol `u`, but whose *value* does not use the symbol `u`. So, even if we could get the presuppositions to go through, it would be ***wrong*** to use something like `Φ || H = H' in TELE`.

What we've done, on the contrary, is even better. We've characterized the *computational* freeness of the *programs* `H, A` from the name/symbol `u`, since they cannot possibly depend on it when it is not possible to distinguish any `u in Top[expr]` from any `v in Top[expr]`. In other words, the `Top[τ]` refinement here *guarantees* that `u` is irrelevant in the part of the telescope in which it would not make sense.

@freebroccolo @jozefg

**Comment by jonsterling** [comment]
I'm actually not sure about whether the meanings of the judgments discussed at the beginning are inductive. It may be coinductive... If anybody has any instincts about this, they are welcome.

**Comment by jozefg** [comment]
Huh, this is really sweet. It really remind me of the avoidance problem that comes up when formalizing module system. There the usual approach is to specify that an equivalent, non-capturing, `A` must exist. So the rule would be something like

        Φ || A'' in D[type]
        Φ, u : Top[expr] || A = A'' in D[type]
        Φ, u : Top[expr] || A'' = A' in D[type]
        Φ, u : Top[expr] || H = H' in TELE
    ------------------------------------------------------------------------
       Φ, u : D[expr] || snoc[u](H; A) = snoc[u](H'; A') in TELE

However here this is completely dead in the water, `D[type]` is way too fine grained. If we opted for a much coarser (computational) equivalence I think this approach may also work?

While I haven't attempted to prove this formally though I think your correct, that meaning you defined certainly decreases `Υ` since you just have to explain the meaning of `u : R` if `Υ = Υ', u : R` if under `Υ` not the full `Υ'`. Am I correct in identifying this as being very related to NuPRL like sequents with the added wrinkle that you have to respect the refinement becoming more fine grained (the lattice subtyping you alluded to)?

**Comment by jonsterling** [comment]
@jozefg Regarding your proposed rule, yes, something like that would be possible. As for equivalence of types, the example is just a case of using this as a logical framework, so using the discrete refinement for types is fine (though, in practice, one would pick something else perhaps). I think that in the case of this example, we needn't go as far as the rule you've proposed, however, since it seems like the computational irrelevance of the symbol is enough, and we may not even need the syntactic irrelevance.

Can you elaborate a bit more on why you think that the definition at the beginning is inductive? I would love to find out that it is, but I am not certain.

The difference between this, btw, and Nuprl sequents is that those are sequents with respect to variable contexts, and so they are given meaning via substitution & functionality, whereas the `Φ || ...` judgments are given meaning only through renaming. In general, I think you are right to show that "Φ || φ refines τ", I *only* need to consider the renamings `Φ --> Φ'` such that `Φ'` is the same length as `Φ` but may involve subtyping.

**Comment by jonsterling** [comment]
Hmmm, I've been trying to work this out in Agda, and I'm getting worried it's not possible to explain these judgments predicatively.

**Comment by jonsterling** [comment]
I think I have a radically different proposal for how all this can work, which I'll try writing up tomorrow.

**Comment by jozefg** [comment]
That's fair.. and hm. I may have spoken hastily. I got sucked into thinking of symbols as being given meaning through substitution. My original intuition that it would be inductive came from the fact that this meaning looked a lot like the one that's come up with logical relations for store but a bit less recursive since a telescope could only refer to prior components..

I'll definitely have to read your proposal and this paper more carefully.. It's certainly more fun than cramming for my probability exam on Monday :)

**Comment by jonsterling** [comment]
@jozefg The more I think about it, I don't think know if it actually makes sense to refine symbols. There really is no meaning there, since refinements are fundamentally about closed terms.

It may make sense to go back to the drawing board and leave symbols & symbol contexts unrefined, and express refinement only for terms (and then, through the logical relations-style argument, for variables). That of course scuttles the approach described in this ticket, but at this time of night, I'm not actually confident that it would have worked! That is, I don't actually think that having `u:Top[expr]` actually means that something can't depend on the symbol `u`; I don't think it means anything at all..

As for the case study of refining telescopes, I believe we'll have to switch to the approach that you brought up—where you show that the term is equal to the "weakening" of another term in order to demonstrate independence from a symbol.

You may want to defer reading the paper until I've reworked it ;-)

**Comment by jozefg** [comment]
@jonsterling Maybe I'm missing something, but maybe there is still some utility for having symbols belonging to a refinement. If you want to represent a language with references through refinements then you need to be able to explain when `get[u]` belongs to some `R refines expr` but the only thing I can think to say here is that `get[u] in R` if `u : R` or something to that effect. Would that be a sane thing to say?

It is confusing though because there is no real "data" associated with a symbol for us to claim it belongs to one refinement more than any other.. it simply is because we say it is and all that really matters is that we consistently treat it as belonging to one refinement or another. That prevents us from claiming that `get[u]` belongs to two disjoint PERs or something equally silly.

**Comment by jonsterling** [comment]
I will respond in more detail later, but we should not say that get[u] belongs to a type by virtue of the type of u, right? We would say that it belongs to a type because it is computationally equivalent to some term which is "clearly" of that type. It's a bit confusing, but unless we intend to switch to a verifications-and-uses style meaning theory, I think we have to stick to computational justifications of membership.

**Comment by jozefg** [comment]
@jonsterling Ah that makes sense, nvm.

**Comment by jonsterling** [comment]
Ehh, no worries! :) I've got turned around several times in the past few days on this stuff...

I'm going to close this ticket and open a new one for redoing the theory in the way I proposed.
